#ifndef _de_petanqueturniermanager_addin_GlobalAddIn_
#define _de_petanqueturniermanager_addin_GlobalAddIn_


#include <com/sun/star/uno/XInterface.idl>
#include <com/sun/star/table/XCellRange.idl>
#include <com/sun/star/sheet/XVolatileResult.idl>

// https://api.libreoffice.org/docs/idl/ref/servicecom_1_1sun_1_1star_1_1sheet_1_1AddIn.html

module de { module petanqueturniermanager { module addin {

  interface XGlobal {
    string ptmstringproperty([in] string propname); // return string value of property
    long ptmintproperty([in] string propname); // return int value of property
    string ptmturniersystem ();
  };

}; }; };


module de { module petanqueturniermanager { module addin {
  service GlobalAddIn : XGlobal;
}; }; };


#endif