#ifndef __de_petanqueturniermanager_petanqueturniermanager_idl__
#define __de_petanqueturniermanager_petanqueturniermanager_idl__

#include <com/sun/star/task/XJobExecutor.idl>
// Package pfad de/petanqueturniermanager
module de { module petanqueturniermanager {
	service PetanqueTurnierManager : com::sun::star::task::XJobExecutor;
 }; };
#endif
